export const EMAIL_TEMPLATE_VARIABLE_KEYS = [
  'empresa.nome',
  'empresa.razaoSocial',
  'empresa.nomeFantasia',
  'empresa.cnpj',
  'empresa.email',
  'empresa.telefone',
  'empresa.endereco',
  'cliente.nome',
  'cliente.email',
  'cliente.telefone',
  'cliente.empresa',
  'cliente.documento',
  'orcamento.titulo',
  'orcamento.valor',
  'orcamento.valorFormatado',
  'orcamento.descricao',
  'orcamento.validade',
  'orcamento.validadeFormatada',
  'orcamento.linkArquivo',
  'usuario.nome',
  'usuario.email',
] as const;

export type EmailTemplateVariableKey = (typeof EMAIL_TEMPLATE_VARIABLE_KEYS)[number];

export const EMAIL_TEMPLATE_VARIABLE_LABELS: Record<EmailTemplateVariableKey, string> = {
  'empresa.nome': 'Empresa — nome',
  'empresa.razaoSocial': 'Empresa — razão social',
  'empresa.nomeFantasia': 'Empresa — nome fantasia',
  'empresa.cnpj': 'Empresa — CNPJ',
  'empresa.email': 'Empresa — e-mail',
  'empresa.telefone': 'Empresa — telefone',
  'empresa.endereco': 'Empresa — endereço',
  'cliente.nome': 'Cliente — nome',
  'cliente.email': 'Cliente — e-mail',
  'cliente.telefone': 'Cliente — telefone',
  'cliente.empresa': 'Cliente — empresa',
  'cliente.documento': 'Cliente — documento',
  'orcamento.titulo': 'Orçamento — título',
  'orcamento.valor': 'Orçamento — valor (número)',
  'orcamento.valorFormatado': 'Orçamento — valor formatado',
  'orcamento.descricao': 'Orçamento — descrição',
  'orcamento.validade': 'Orçamento — validade (ISO)',
  'orcamento.validadeFormatada': 'Orçamento — validade formatada',
  'orcamento.linkArquivo': 'Orçamento — link do PDF',
  'usuario.nome': 'Usuário — nome',
  'usuario.email': 'Usuário — e-mail',
};
